# Generated by Django 2.2.1 on 2019-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='serves_hot_dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='serves_pizza',
            field=models.BooleanField(default=False),
        ),
    ]
