# Generated by Django 2.2.1 on 2019-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
